net-il-mio-fotoalbum/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using la_mia_pizzeria_static;
using la_mia_pizzeria_static.Models;

namespace net_il_mio_fotoalbum.Controllers
{
    public class CategoryController : Controller
    {
        private readonly PictureContext _context;

        public CategoryController(PictureContext context)
        {
            _context = context;
        }

        // GET: Category
        public async Task<IActionResult> Index()
        {
            return View(await _context.Categories.ToListAsync());
        }

        // GET: Category/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Categories
                .FirstOrDefaultAsync(m => m.Id == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // GET: Category/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Category/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name")] Category category)
        {
            if (ModelState.IsValid)
            {
                _context.Add(category);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: Category/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Categories.FindAsync(id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        // POST: Category/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name")] Category category)
        {
            if (id != category.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(category);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CategoryExists(category.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: Category/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Categories
                .FirstOrDefaultAsync(m => m.Id == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // POST: Category/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var category = await _context.Categories.FindAsync(id);
            if (category != null)
            {
                _context.Categories.Remove(category);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CategoryExists(int id)
        {
            return _context.Categories.Any(e => e.Id == id);
        }
    }
}

net-il-mio-fotoalbum/Controllers/PictureController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using la_mia_pizzeria_static;
using la_mia_pizzeria_static.Models;
using Microsoft.AspNetCore.Authorization;
using Azure;
using Microsoft.Extensions.Hosting;

namespace net_il_mio_fotoalbum.Controllers
{
    [Authorize]
    public class PictureController : Controller
    {
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            using (PictureContext db = new PictureContext()) {
                List <Picture> pictureList = db.Pictures.ToList();
            return View(pictureList);
            }
            
        }

        [HttpGet]
        public IActionResult Show(int id)
        {
            using(PictureContext db = new PictureContext())
            {
                Picture pic = db.Pictures.Where(p => p.Id == id).Include(p => p.Categories).FirstOrDefault();
                return View(pic);
            }
        }

        [HttpGet]
        public IActionResult Create() 
        { 
            PictureFormModel model = new PictureFormModel();
            model.Picture = new Picture();
            model.CreateCategories();
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public IActionResult Create(PictureFormModel data)
        {
            // Aggiungere log per vedere se il file viene caricato
            if (data.ImageFormFile != null)
            {
                Console.WriteLine($"File size: {data.ImageFormFile.Length}");
            }
            else
            {
                Console.WriteLine("No file uploaded.");
            }

            if (!ModelState.IsValid)
            {
                // Log degli errori del ModelState
                foreach (var error in ModelState.Values.SelectMany(v => v.Errors))
                {
                    Console.WriteLine(error.ErrorMessage);
                }

                // Ritorniamo "data" alla view così che la form abbia di nuovo i dati inseriti
                using (PictureContext db = new PictureContext())
                {
                    data.CreateCategories();
                    return View("Create", data);
                }
            }

            // Gestione del file caricato
            if (data.ImageFormFile != null && data.ImageFormFile.Length > 0)
            {
                using (var memoryStream = new MemoryStream())
                {
                    data.ImageFormFile.CopyTo(memoryStream);
                    data.Picture.Image = memoryStream.ToArray();
                }
            }
            else
            {
                ModelState.AddModelError("ImageFormFile", "Per favore carica un'immagine.");
                using (PictureContext db = new PictureContext())
                {
                    data.CreateCategories();
                    return View("Create", data);
                }
            }

            using (var db = new PictureContext())
            {
                if (data.SelectedCategories != null)
                {
                    data.Picture.Categories = new List<Category>();
                    foreach (var tagId in data.SelectedCategories)
                    {
                        int id = int.Parse(tagId);
                        var tag = db.Categories.FirstOrDefault(t => t.Id == id); 
                        if (tag != null)
                        {
                            data.Picture.Categories.Add(tag);
                        }
                    }
                }
                db.Pictures.Add(data.Picture);
                db.SaveChanges();
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            using (var db = new PictureContext())
            {
                Picture picToEdit = db.Pictures.Where(p => p.Id == id).Include(p => p.Categories).FirstOrDefault();
                if (picToEdit == null)
                {
                    return NotFound();
                }
                else
                {
                    PictureFormModel model = new PictureFormModel();
                    model.Picture = picToEdit;
                    model.CreateCategories();

                    return View(model);
                }
            }
        }

        [HttpPost]
        public IActionResult Edit(int id, PictureFormModel data)
        {
            if (!ModelState.IsValid)
            {
                using (PictureContext db = new PictureContext())
                {
                    data.CreateCategories();
                    return View("Edit", data);
                }
            }

            using (var db = new PictureContext())
            {
                Picture p = db.Pictures.Where(p => p.Id == id).Include(i => i.Categories).FirstOrDefault();

                if (p != null)
                {
                    p.Title = data.Picture.Title;
                    p.Description = data.Picture.Description;
                    if (data.ImageFormFile != null && data.ImageFormFile.Length > 0)
                    {
                        using (var memoryStream = new MemoryStream())
                        {
                            data.ImageFormFile.CopyTo(memoryStream);
                            data.Picture.Image = memoryStream.ToArray();
                        }
                    }
                    if(data.Picture.Image != null)
                         p.Image = data.Picture.Image;

                    p.Visible = data.Picture.Visible;
                    p.Categories.Clear();
                    if (data.SelectedCategories != null)
                    {
                        foreach (var ingId in data.SelectedCategories)
                        {
                            int selectedId = int.Parse(ingId);
                            Category newIng = db.Categories.Where(i => i.Id == selectedId).FirstOrDefault();
                            p.Categories.Add(newIng);
                        }
                    }

                    db.SaveChanges();
                    return RedirectToAction("Index");
                }

            }
            return NotFound();
        }

        [HttpPost]
        public IActionResult Delete(int id)
        {
            using (var db = new PictureContext())
            {
                Picture toDelete = db.Pictures.Where(p => p.Id == id).FirstOrDefault();

                if (toDelete != null)
                {
                    db.Pictures.Remove(toDelete);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }

                return NotFound();
            }
        }
    }
}

net-il-mio-fotoalbum/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
@using Microsoft.AspNetCore.Identity

@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - net_il_mio_fotoalbum</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="~/net_il_mio_fotoalbum.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">net_il_mio_fotoalbum</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1 justify-content-end">
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Picture" asp-action="Index">Gestionale Foto</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Categorie</a>
                            </li>
                        }
                        <partial name="_LoginPartial" />
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - net_il_mio_fotoalbum - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>